
# This file is automatically generated, you probably don't want to edit this

likertplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            liks = NULL,
            group = NULL,
            type = "centered",
            groupBy = "variable",
            sorting = "none",
            addLabels = TRUE,
            addTotals = TRUE,
            addMedianLine = TRUE,
            reverseLikert = FALSE,
            jamoviTheme = FALSE, ...) {

            super$initialize(
                package="vijLikert",
                name="likertplot",
                requiresData=TRUE,
                ...)

            private$..liks <- jmvcore::OptionVariables$new(
                "liks",
                liks)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "centered",
                    "stacked"),
                default="centered")
            private$..groupBy <- jmvcore::OptionList$new(
                "groupBy",
                groupBy,
                options=list(
                    "variable",
                    "group"),
                default="variable")
            private$..sorting <- jmvcore::OptionList$new(
                "sorting",
                sorting,
                options=list(
                    "none",
                    "ascending",
                    "descending"),
                default="none")
            private$..addLabels <- jmvcore::OptionBool$new(
                "addLabels",
                addLabels,
                default=TRUE)
            private$..addTotals <- jmvcore::OptionBool$new(
                "addTotals",
                addTotals,
                default=TRUE)
            private$..addMedianLine <- jmvcore::OptionBool$new(
                "addMedianLine",
                addMedianLine,
                default=TRUE)
            private$..reverseLikert <- jmvcore::OptionBool$new(
                "reverseLikert",
                reverseLikert,
                default=FALSE)
            private$..jamoviTheme <- jmvcore::OptionBool$new(
                "jamoviTheme",
                jamoviTheme,
                default=FALSE)

            self$.addOption(private$..liks)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..groupBy)
            self$.addOption(private$..sorting)
            self$.addOption(private$..addLabels)
            self$.addOption(private$..addTotals)
            self$.addOption(private$..addMedianLine)
            self$.addOption(private$..reverseLikert)
            self$.addOption(private$..jamoviTheme)
        }),
    active = list(
        liks = function() private$..liks$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        groupBy = function() private$..groupBy$value,
        sorting = function() private$..sorting$value,
        addLabels = function() private$..addLabels$value,
        addTotals = function() private$..addTotals$value,
        addMedianLine = function() private$..addMedianLine$value,
        reverseLikert = function() private$..reverseLikert$value,
        jamoviTheme = function() private$..jamoviTheme$value),
    private = list(
        ..liks = NA,
        ..group = NA,
        ..type = NA,
        ..groupBy = NA,
        ..sorting = NA,
        ..addLabels = NA,
        ..addTotals = NA,
        ..addMedianLine = NA,
        ..reverseLikert = NA,
        ..jamoviTheme = NA)
)

likertplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Likert Plots",
                refs=list(
                    "ggplots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "liks",
                    "group",
                    "groupBy",
                    "type",
                    "sorting",
                    "addLabels",
                    "addTotals",
                    "addMedianLine",
                    "reverseLikert",
                    "jamoviTheme")))}))

likertplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijLikert",
                name = "likertplot",
                version = c(1,0,0),
                options = options,
                results = likertplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Likert Plots
#'
#' 
#' @param data .
#' @param liks .
#' @param group .
#' @param type .
#' @param groupBy .
#' @param sorting .
#' @param addLabels .
#' @param addTotals .
#' @param addMedianLine .
#' @param reverseLikert .
#' @param jamoviTheme .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
likertplot <- function(
    data,
    liks,
    group,
    type = "centered",
    groupBy = "variable",
    sorting = "none",
    addLabels = TRUE,
    addTotals = TRUE,
    addMedianLine = TRUE,
    reverseLikert = FALSE,
    jamoviTheme = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("likertplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(liks)) liks <- jmvcore::resolveQuo(jmvcore::enquo(liks))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(liks), liks, NULL),
            `if`( ! missing(group), group, NULL))


    options <- likertplotOptions$new(
        liks = liks,
        group = group,
        type = type,
        groupBy = groupBy,
        sorting = sorting,
        addLabels = addLabels,
        addTotals = addTotals,
        addMedianLine = addMedianLine,
        reverseLikert = reverseLikert,
        jamoviTheme = jamoviTheme)

    analysis <- likertplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

