
# This file is automatically generated, you probably don't want to edit this

likertplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            liks = NULL,
            group = NULL,
            type = "centered",
            sorting = "none",
            groupBy = "variable",
            addLabels = TRUE,
            addTotals = TRUE,
            addMedianLine = TRUE,
            reverseLikert = FALSE,
            plotWidth = 600,
            plotHeight = 400,
            textSize = 12,
            plotColor = "BrBG", ...) {

            super$initialize(
                package="vijLikert",
                name="likertplot",
                requiresData=TRUE,
                ...)

            private$..liks <- jmvcore::OptionVariables$new(
                "liks",
                liks,
                required=TRUE,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "centered",
                    "stacked"),
                default="centered")
            private$..sorting <- jmvcore::OptionList$new(
                "sorting",
                sorting,
                options=list(
                    "none",
                    "ascending",
                    "descending"),
                default="none")
            private$..groupBy <- jmvcore::OptionList$new(
                "groupBy",
                groupBy,
                options=list(
                    "variable",
                    "group"),
                default="variable")
            private$..addLabels <- jmvcore::OptionBool$new(
                "addLabels",
                addLabels,
                default=TRUE)
            private$..addTotals <- jmvcore::OptionBool$new(
                "addTotals",
                addTotals,
                default=TRUE)
            private$..addMedianLine <- jmvcore::OptionBool$new(
                "addMedianLine",
                addMedianLine,
                default=TRUE)
            private$..reverseLikert <- jmvcore::OptionBool$new(
                "reverseLikert",
                reverseLikert,
                default=FALSE)
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=300,
                max=800,
                default=600)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=200,
                max=1600,
                default=400)
            private$..textSize <- jmvcore::OptionNumber$new(
                "textSize",
                textSize,
                min=6,
                max=24,
                default=12)
            private$..plotColor <- jmvcore::OptionList$new(
                "plotColor",
                plotColor,
                options=list(
                    "BrBG",
                    "PiYG",
                    "PRGn",
                    "PuOr",
                    "RdBu",
                    "RdGy",
                    "RdYlBu",
                    "RdYlGn",
                    "Spectral"),
                default="BrBG")

            self$.addOption(private$..liks)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..sorting)
            self$.addOption(private$..groupBy)
            self$.addOption(private$..addLabels)
            self$.addOption(private$..addTotals)
            self$.addOption(private$..addMedianLine)
            self$.addOption(private$..reverseLikert)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..textSize)
            self$.addOption(private$..plotColor)
        }),
    active = list(
        liks = function() private$..liks$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        sorting = function() private$..sorting$value,
        groupBy = function() private$..groupBy$value,
        addLabels = function() private$..addLabels$value,
        addTotals = function() private$..addTotals$value,
        addMedianLine = function() private$..addMedianLine$value,
        reverseLikert = function() private$..reverseLikert$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        textSize = function() private$..textSize$value,
        plotColor = function() private$..plotColor$value),
    private = list(
        ..liks = NA,
        ..group = NA,
        ..type = NA,
        ..sorting = NA,
        ..groupBy = NA,
        ..addLabels = NA,
        ..addTotals = NA,
        ..addMedianLine = NA,
        ..reverseLikert = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..textSize = NA,
        ..plotColor = NA)
)

likertplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Likert Plots",
                refs=list(
                    "ggplots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "liks",
                    "group",
                    "groupBy",
                    "type",
                    "sorting",
                    "addLabels",
                    "addTotals",
                    "addMedianLine",
                    "reverseLikert",
                    "jamoviTheme",
                    "plotW",
                    "plotH",
                    "textSize",
                    "plotColor")))}))

likertplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijLikert",
                name = "likertplot",
                version = c(1,0,0),
                options = options,
                results = likertplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Likert Plots
#'
#' 
#' @param data .
#' @param liks .
#' @param group .
#' @param type .
#' @param sorting .
#' @param groupBy .
#' @param addLabels .
#' @param addTotals .
#' @param addMedianLine .
#' @param reverseLikert .
#' @param plotWidth .
#' @param plotHeight .
#' @param textSize .
#' @param plotColor .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
likertplot <- function(
    data,
    liks,
    group,
    type = "centered",
    sorting = "none",
    groupBy = "variable",
    addLabels = TRUE,
    addTotals = TRUE,
    addMedianLine = TRUE,
    reverseLikert = FALSE,
    plotWidth = 600,
    plotHeight = 400,
    textSize = 12,
    plotColor = "BrBG") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("likertplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(liks)) liks <- jmvcore::resolveQuo(jmvcore::enquo(liks))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(liks), liks, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in liks) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- likertplotOptions$new(
        liks = liks,
        group = group,
        type = type,
        sorting = sorting,
        groupBy = groupBy,
        addLabels = addLabels,
        addTotals = addTotals,
        addMedianLine = addMedianLine,
        reverseLikert = reverseLikert,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        textSize = textSize,
        plotColor = plotColor)

    analysis <- likertplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

